name: Deployment Status Check

on:
  workflow_dispatch:
  schedule:
    # Run health check every 6 hours
    - cron: '0 */6 * * *'

jobs:
  health-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check Application Health
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: ${{ secrets.VPS_PORT || 22 }}
        script: |
          echo "🔍 Checking application health..."
          
          # Check PM2 status
          echo "📊 PM2 Status:"
          pm2 status
          
          # Check if application is running
          if pm2 list | grep -q "mmp-garage.*online"; then
            echo "✅ Application is running"
            
            # Check port
            if netstat -tuln | grep -q ":3001"; then
              echo "✅ Port 3001 is listening"
            else
              echo "❌ Port 3001 is not listening"
            fi
            
            # Check local connectivity
            if curl -f -s -m 10 http://localhost:3001 > /dev/null; then
              echo "✅ Local HTTP response successful"
            else
              echo "❌ Local HTTP response failed"
            fi
            
            # Check external connectivity
            if curl -f -s -m 10 https://www.gulf-restaurant.com > /dev/null; then
              echo "✅ External HTTPS response successful"
            else
              echo "❌ External HTTPS response failed"
            fi
            
          else
            echo "❌ Application is not running"
            echo "📋 Recent logs:"
            pm2 logs mmp-garage --lines 10
          fi
          
          # System resource check
          echo "💾 System Resources:"
          echo "Memory usage:"
          free -h
          echo "Disk usage:"
          df -h /home/gulf-restaurant
          
          # Check log file sizes
          echo "📁 Log file sizes:"
          ls -lh /home/gulf-restaurant/logs/ 2>/dev/null || echo "No log files found"
          
          echo "🏁 Health check completed"

  notify-status:
    runs-on: ubuntu-latest
    needs: health-check
    if: failure()
    
    steps:
    - name: Create Issue on Failure
      uses: actions/github-script@v7
      with:
        script: |
          const title = `🚨 Deployment Health Check Failed - ${new Date().toISOString()}`;
          const body = `
          ## Deployment Health Check Failed
          
          **Time**: ${new Date().toISOString()}
          **Workflow**: ${context.workflow}
          **Run ID**: ${context.runId}
          
          ### What happened?
          The automated health check for the VPS deployment failed. This could indicate:
          
          - Application is not running
          - Port 3001 is not accessible
          - External domain is not responding
          - System resource issues
          
          ### Next Steps
          1. Check the [workflow logs](${context.payload.repository.html_url}/actions/runs/${context.runId})
          2. SSH into the VPS and run manual diagnostics
          3. Check PM2 status: \`pm2 status\`
          4. Check application logs: \`pm2 logs mmp-garage\`
          5. Restart if necessary: \`pm2 restart mmp-garage\`
          
          ### Manual Health Check Commands
          \`\`\`bash
          # SSH into VPS
          ssh gulf-restaurant@${process.env.VPS_HOST || 'your-vps-ip'}
          
          # Check application status
          pm2 status
          pm2 logs mmp-garage --lines 20
          
          # Check system resources
          free -h
          df -h
          
          # Test connectivity
          curl -I http://localhost:3001
          curl -I https://www.gulf-restaurant.com
          \`\`\`
          
          This issue was automatically created by the deployment monitoring system.
          `;
          
          github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: title,
            body: body,
            labels: ['deployment', 'health-check', 'automated']
          });